apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2  # Number of Pods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Maximum 1 Pod can be unavailable during update
      maxSurge: 1        # Maximum 1 extra Pod can be created during update
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: si2502/todo-webapp:v6  
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: FLASK_ENV
              value: production

          # Health Probes Configuration
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5  # Delay before first check
            periodSeconds: 10  # Check every 10s
            failureThreshold: 3  # Mark as unhealthy if it fails 3 times

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
      imagePullSecrets:
          - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
spec:
  replicas: 1  # Ensures 2 replicas are always running
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: si2502/todo-webapp:v6
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: FLASK_ENV
              value: production
