apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
  namespace: default
spec:
  containers:
  - name: crashloop
    image: busybox:2
    command: ["sh", "-c", "exit 1"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: image-test
  namespace: default
spec:
  containers:
  - name: bad-image
    image: nonexistent-image:latest